In [1]:
import pandas as pd
import csv, json

In [2]:
vac1516="dataView1340_3.xls"
vac1617="dataView2065_3.xls"
vac1718="dataView2164_3.xls"
vac1819="dataView2246_3.xls"

vac1516_df=pd.read_excel(vac1516)
vac1617_df=pd.read_excel(vac1617)
vac1718_df=pd.read_excel(vac1718)
vac1819_df=pd.read_excel(vac1819)

In [3]:
vac1516_df.head(20)
del vac1516_df["Unnamed: 2"]

In [4]:
vac1516_df.head()

cleaned1516=vac1516_df.drop(columns=["Influenza vaccination (General Population) - Age",
                        "Unnamed: 3","Unnamed: 4","Unnamed: 6","Unnamed: 99","Unnamed: 100","Unnamed: 101","Unnamed: 102","Unnamed: 103","Unnamed: 104",
                        "Unnamed: 105","Unnamed: 106","Unnamed: 7","Unnamed: 8","Unnamed: 9","Unnamed: 10","Unnamed: 12","Unnamed: 13","Unnamed: 14"
                                    ,"Unnamed: 15","Unnamed: 16","Unnamed: 18","Unnamed: 19","Unnamed: 20","Unnamed: 21","Unnamed: 22",
                                    "Unnamed: 24","Unnamed: 25","Unnamed: 26","Unnamed: 27","Unnamed: 28",
                                    "Unnamed: 30","Unnamed: 31","Unnamed: 32","Unnamed: 33","Unnamed: 34",
                                    "Unnamed: 36","Unnamed: 37","Unnamed: 38","Unnamed: 39","Unnamed: 40",
                                    "Unnamed: 42","Unnamed: 43","Unnamed: 44","Unnamed: 45","Unnamed: 46",
                                    "Unnamed: 48","Unnamed: 49","Unnamed: 50","Unnamed: 51","Unnamed: 52",
                                    "Unnamed: 54","Unnamed: 55","Unnamed: 56","Unnamed: 57","Unnamed: 58",
                                    "Unnamed: 91","Unnamed: 92","Unnamed: 93","Unnamed: 94","Unnamed: 95",
                                    "Unnamed: 60","Unnamed: 61","Unnamed: 62","Unnamed: 63","Unnamed: 64",
                                    "Unnamed: 66","Unnamed: 67","Unnamed: 68","Unnamed: 69","Unnamed: 70",
                                    "Unnamed: 72","Unnamed: 73","Unnamed: 74","Unnamed: 75","Unnamed: 76",
                                    "Unnamed: 78","Unnamed: 79","Unnamed: 80","Unnamed: 81","Unnamed: 82",
                                    "Unnamed: 84","Unnamed: 86","Unnamed: 87","Unnamed: 88",
                                    "Unnamed: 89","Unnamed: 90","Unnamed: 96","Unnamed: 97","Unnamed: 98",
                                    "Unnamed: 107","Unnamed: 108", "Influenza vaccination (General Population) - Race/ethnicity"])

cleaned1516=cleaned1516.drop([0,1],axis=0)
cleaned1516.head()

cleaned1516.rename(columns={"Unnamed: 0":"Location of Immunization"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 5":"≥ 6 months"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 11":"6 months - 17 years"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 17":"6 months - 4 years"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 23":"5 - 12 years"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 29":"13 - 17 years"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 35":"≥ 18 years"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 41":"18 - 64 years"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 59":"18 - 49 years"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 77":"50 -64 years"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 83":"≥ 65 years"},inplace=True)

del cleaned1516["Unnamed: 47"]
del cleaned1516["Unnamed: 53"]
del cleaned1516["Unnamed: 65"]
del cleaned1516["Unnamed: 71"]


cleaned1516.insert(0, 'Flu Season', '2015-2016')

In [5]:
cleaned1516.head(20)

,Flu Season,Location of Immunization,≥ 6 months,6 months - 17 years,6 months - 4 years,5 - 12 years,13 - 17 years,≥ 18 years,18 - 64 years,18 - 49 years,50 -64 years,≥ 65 years
2,2015-2016,Alabama,7822,2375,720,1121,534,5447,3719,1992,1727,1728
3,2015-2016,Alaska,4740,2287,681,955,651,2453,1801,946,855,652
4,2015-2016,Arizona,9739,2418,678,983,757,7321,3933,1859,2074,3388
5,2015-2016,Arkansas,5694,1896,566,797,533,3798,2017,850,1167,1781
6,2015-2016,California,9488,2437,834,1020,583,7051,5349,3452,1897,1702
7,2015-2016,Colorado,10600,1846,584,799,463,8754,5807,3057,2750,2947
8,2015-2016,Connecticut,11758,2344,706,1110,528,9414,5764,2620,3144,3650
9,2015-2016,Delaware,5144,2089,606,941,542,3055,1969,992,977,1086
10,2015-2016,District of Columbia,4624,2425,833,1007,585,2199,1255,542,713,944
11,2015-2016,Florida,15430,2354,725,1015,614,13076,7698,3929,3769,5378
12,2015-2016,Georgia,5874,2466,788,1131,547,3408,2140,1102,1038,1268
13,2015-2016,Hawaii,7604,2126,656,964,506,5478,3625,1888,1737,1853
14,2015-2016,Idaho,6052,1669,493,702,474,4383,2750,1413,1337,1633
15,2015-2016,Illinois,7893,4387,1347,1832,1208,3506,2338,1302,1036,1168
16,2015-2016,Indiana,6760,1938,575,845,518,4822,2938,1448,1490,1884
17,2015-2016,Iowa,7436,2242,671,1040,531,5194,3294,1616,1678,1900
18,2015-2016,Kansas,12767,1675,509,670,496,11092,7217,3739,3478,3875
19,2015-2016,Kentucky,8733,1934,609,864,461,6799,4664,2383,2281,2135
20,2015-2016,Louisiana,6240,2208,626,965,617,4032,2436,1124,1312,1596
21,2015-2016,Maine,9654,2182,615,1023,544,7472,4631,2097,2534,2841

In [6]:
sum_col = cleaned1516['≥ 6 months'] + cleaned1516['6 months - 17 years'] + cleaned1516['≥ 18 years'] 
cleaned1516['Total Vaccinated'] = sum_col
cleaned1516.head()

,Flu Season,Location of Immunization,≥ 6 months,6 months - 17 years,6 months - 4 years,5 - 12 years,13 - 17 years,≥ 18 years,18 - 64 years,18 - 49 years,50 -64 years,≥ 65 years,Total Vaccinated
2,2015-2016,Alabama,7822,2375,720,1121,534,5447,3719,1992,1727,1728,15644
3,2015-2016,Alaska,4740,2287,681,955,651,2453,1801,946,855,652,9480
4,2015-2016,Arizona,9739,2418,678,983,757,7321,3933,1859,2074,3388,19478
5,2015-2016,Arkansas,5694,1896,566,797,533,3798,2017,850,1167,1781,11388
6,2015-2016,California,9488,2437,834,1020,583,7051,5349,3452,1897,1702,18976

In [7]:
cleaned1516state = cleaned1516.iloc[:51]
cleaned1516state.head(52)

,Flu Season,Location of Immunization,≥ 6 months,6 months - 17 years,6 months - 4 years,5 - 12 years,13 - 17 years,≥ 18 years,18 - 64 years,18 - 49 years,50 -64 years,≥ 65 years,Total Vaccinated
2,2015-2016,Alabama,7822,2375,720,1121,534,5447,3719,1992,1727,1728,15644
3,2015-2016,Alaska,4740,2287,681,955,651,2453,1801,946,855,652,9480
4,2015-2016,Arizona,9739,2418,678,983,757,7321,3933,1859,2074,3388,19478
5,2015-2016,Arkansas,5694,1896,566,797,533,3798,2017,850,1167,1781,11388
6,2015-2016,California,9488,2437,834,1020,583,7051,5349,3452,1897,1702,18976
7,2015-2016,Colorado,10600,1846,584,799,463,8754,5807,3057,2750,2947,21200
8,2015-2016,Connecticut,11758,2344,706,1110,528,9414,5764,2620,3144,3650,23516
9,2015-2016,Delaware,5144,2089,606,941,542,3055,1969,992,977,1086,10288
10,2015-2016,District of Columbia,4624,2425,833,1007,585,2199,1255,542,713,944,9248
11,2015-2016,Florida,15430,2354,725,1015,614,13076,7698,3929,3769,5378,30860
12,2015-2016,Georgia,5874,2466,788,1131,547,3408,2140,1102,1038,1268,11748
13,2015-2016,Hawaii,7604,2126,656,964,506,5478,3625,1888,1737,1853,15208
14,2015-2016,Idaho,6052,1669,493,702,474,4383,2750,1413,1337,1633,12104
15,2015-2016,Illinois,7893,4387,1347,1832,1208,3506,2338,1302,1036,1168,15786
16,2015-2016,Indiana,6760,1938,575,845,518,4822,2938,1448,1490,1884,13520
17,2015-2016,Iowa,7436,2242,671,1040,531,5194,3294,1616,1678,1900,14872
18,2015-2016,Kansas,12767,1675,509,670,496,11092,7217,3739,3478,3875,25534
19,2015-2016,Kentucky,8733,1934,609,864,461,6799,4664,2383,2281,2135,17466
20,2015-2016,Louisiana,6240,2208,626,965,617,4032,2436,1124,1312,1596,12480
21,2015-2016,Maine,9654,2182,615,1023,544,7472,4631,2097,2534,2841,19308
22,2015-2016,Maryland,14683,2782,869,1262,651,11901,7468,3511,3957,4433,29366
23,2015-2016,Massachusetts,7863,2656,816,1223,617,5207,3673,2093,1580,1534,15726
24,2015-2016,Michigan,9405,1632,551,639,442,7773,5398,2932,2466,2375,18810
25,2015-2016,Minnesota,13846,2447,757,1014,676,11399,8027,4502,3525,3372,27692
26,2015-2016,Mississippi,6424,2322,697,1042,583,4102,2659,1426,1233,1443,12848
27,2015-2016,Missouri,7255,1822,572,744,506,5433,3278,1682,1596,2155,14510
28,2015-2016,Montana,6873,1965,582,831,552,4908,2997,1449,1548,1911,13746
29,2015-2016,Nebraska,13535,1974,564,775,635,11561,7574,4047,3527,3987,27070
30,2015-2016,Nevada,3752,1758,528,707,523,1994,1259,671,588,735,7504
31,2015-2016,New Hampshire,6924,1966,570,909,487,4958,2999,1284,1715,1959,13848
32,2015-2016,New Jersey,7818,2758,885,1100,773,5060,3414,1741,1673,1646,15636
33,2015-2016,New Mexico,6395,1891,531,842,518,4504,2916,1451,1465,1588,12790
34,2015-2016,New York,22196,5065,1732,2131,1202,17131,11474,5969,5505,5657,44392
35,2015-2016,North Carolina,7226,2240,724,984,532,4986,3520,2008,1512,1466,14452
36,2015-2016,North Dakota,5805,1667,531,658,478,4138,2686,1360,1326,1452,11610
37,2015-2016,Ohio,10516,1814,533,773,508,8702,5345,2605,2740,3357,21032
38,2015-2016,Oklahoma,6324,1712,527,700,485,4612,2677,1302,1375,1935,12648
39,2015-2016,Oregon,5231,1915,545,828,542,3316,2184,1244,940,1132,10462
40,2015-2016,Pennsylvania,10370,4872,1496,2040,1336,5498,3895,2118,1777,1603,20740
41,2015-2016,Rhode Island,6784,2738,785,1393,560,4046,2532,1128,1404,1514,13568
42,2015-2016,South Carolina,11089,2599,797,1173,629,8490,5045,2478,2567,3445,22178
43,2015-2016,South Dakota,7041,2139,653,971,515,4902,3115,1547,1568,1787,14082
44,2015-2016,Tennessee,5803,1862,565,782,515,3941,2438,1180,1258,1503,11606
45,2015-2016,Texas,21564,12125,3560,5001,3564,9439,5810,3195,2615,3629,43128
46,2015-2016,Utah,8627,1702,534,610,558,6925,5003,3161,1842,1922,17254
47,2015-2016,Vermont,6678,1964,562,975,427,4714,3191,1480,1711,1523,13356
48,2015-2016,Virginia,9032,2799,901,1263,635,6233,4248,2260,1988,1985,18064
49,2015-2016,Washington,14147,2428,766,1029,633,11719,7380,3705,3675,4339,28294
50,2015-2016,West Virginia,7627,2064,637,920,507,5563,3854,2025,1829,1709,15254
51,2015-2016,Wisconsin,5460,1943,575,850,518,3517,2331,1181,1150,1186,10920
52,2015-2016,Wyoming,5668,1927,546,872,509,3741,2113,902,1211,1628,11336

In [8]:
code_col = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL", "GA", 
          "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", 
          "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", 
          "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", 
          "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]
cleaned1516state['Code'] = code_col
cleaned1516state.head()

C:\Users\sarah\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Flu Season,Location of Immunization,≥ 6 months,6 months - 17 years,6 months - 4 years,5 - 12 years,13 - 17 years,≥ 18 years,18 - 64 years,18 - 49 years,50 -64 years,≥ 65 years,Total Vaccinated,Code
2,2015-2016,Alabama,7822,2375,720,1121,534,5447,3719,1992,1727,1728,15644,AL
3,2015-2016,Alaska,4740,2287,681,955,651,2453,1801,946,855,652,9480,AK
4,2015-2016,Arizona,9739,2418,678,983,757,7321,3933,1859,2074,3388,19478,AZ
5,2015-2016,Arkansas,5694,1896,566,797,533,3798,2017,850,1167,1781,11388,AR
6,2015-2016,California,9488,2437,834,1020,583,7051,5349,3452,1897,1702,18976,CA

In [9]:
vac1617_df.head()
cleaned1617=vac1617_df.drop(columns=["Unnamed: 2","Influenza vaccination (General Population) - Age",
                        "Unnamed: 3","Unnamed: 4","Unnamed: 6","Unnamed: 99","Unnamed: 100","Unnamed: 101","Unnamed: 102","Unnamed: 103","Unnamed: 104",
                        "Unnamed: 105","Unnamed: 106","Unnamed: 7","Unnamed: 8","Unnamed: 9","Unnamed: 10","Unnamed: 12","Unnamed: 13","Unnamed: 14"
                                    ,"Unnamed: 15","Unnamed: 16","Unnamed: 18","Unnamed: 19","Unnamed: 20","Unnamed: 21","Unnamed: 22",
                                    "Unnamed: 24","Unnamed: 25","Unnamed: 26","Unnamed: 27","Unnamed: 28",
                                    "Unnamed: 30","Unnamed: 31","Unnamed: 32","Unnamed: 33","Unnamed: 34",
                                    "Unnamed: 36","Unnamed: 37","Unnamed: 38","Unnamed: 39","Unnamed: 40",
                                    "Unnamed: 42","Unnamed: 43","Unnamed: 44","Unnamed: 45","Unnamed: 46",
                                    "Unnamed: 48","Unnamed: 49","Unnamed: 50","Unnamed: 51","Unnamed: 52",
                                    "Unnamed: 54","Unnamed: 55","Unnamed: 56","Unnamed: 57","Unnamed: 58",
                                    "Unnamed: 91","Unnamed: 92","Unnamed: 93","Unnamed: 94","Unnamed: 95",
                                    "Unnamed: 60","Unnamed: 61","Unnamed: 62","Unnamed: 63","Unnamed: 64",
                                    "Unnamed: 66","Unnamed: 67","Unnamed: 68","Unnamed: 69","Unnamed: 70",
                                    "Unnamed: 72","Unnamed: 73","Unnamed: 74","Unnamed: 75","Unnamed: 76",
                                    "Unnamed: 78","Unnamed: 79","Unnamed: 80","Unnamed: 81","Unnamed: 82",
                                    "Unnamed: 84","Unnamed: 86","Unnamed: 87","Unnamed: 88",
                                    "Unnamed: 89","Unnamed: 90","Unnamed: 96","Unnamed: 97","Unnamed: 98",
                                    "Unnamed: 107","Unnamed: 108", "Influenza vaccination (General Population) - Race/ethnicity"])

cleaned1617=cleaned1617.drop([0,1],axis=0)
cleaned1617.head()

cleaned1617.rename(columns={"Unnamed: 0":"Location of Immunization"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 5":"≥ 6 months"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 11":"6 months - 17 years"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 17":"6 months - 4 years"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 23":"5 - 12 years"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 29":"13 - 17 years"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 35":"≥ 18 years"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 41":"18 - 64 years"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 59":"18 - 49 years"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 77":"50 -64 years"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 83":"≥ 65 years"},inplace=True)

del cleaned1617["Unnamed: 47"]
del cleaned1617["Unnamed: 53"]
del cleaned1617["Unnamed: 65"]
del cleaned1617["Unnamed: 71"]

cleaned1617.insert(0, 'Flu Season', '2016-2017')

In [10]:
cleaned1617.head()

,Flu Season,Location of Immunization,≥ 6 months,6 months - 17 years,6 months - 4 years,5 - 12 years,13 - 17 years,≥ 18 years,18 - 64 years,18 - 49 years,50 -64 years,≥ 65 years
2,2016-2017,Alabama,7901,2555,757,1196,602,5346,3393,1774,1619,1953
3,2016-2017,Alaska,4998,2238,688,971,579,2760,1989,980,1009,771
4,2016-2017,Arizona,11261,2357,706,1030,621,8904,4950,2486,2464,3954
5,2016-2017,Arkansas,6418,2303,691,1027,585,4115,2075,896,1179,2040
6,2016-2017,California,8010,3095,1059,1348,688,4915,3726,2436,1290,1189

In [11]:
sum_col = cleaned1617['≥ 6 months'] + cleaned1617['6 months - 17 years'] + cleaned1617['≥ 18 years'] 
cleaned1617['Total Vaccinated'] = sum_col
cleaned1617.head()

,Flu Season,Location of Immunization,≥ 6 months,6 months - 17 years,6 months - 4 years,5 - 12 years,13 - 17 years,≥ 18 years,18 - 64 years,18 - 49 years,50 -64 years,≥ 65 years,Total Vaccinated
2,2016-2017,Alabama,7901,2555,757,1196,602,5346,3393,1774,1619,1953,15802
3,2016-2017,Alaska,4998,2238,688,971,579,2760,1989,980,1009,771,9996
4,2016-2017,Arizona,11261,2357,706,1030,621,8904,4950,2486,2464,3954,22522
5,2016-2017,Arkansas,6418,2303,691,1027,585,4115,2075,896,1179,2040,12836
6,2016-2017,California,8010,3095,1059,1348,688,4915,3726,2436,1290,1189,16020

In [12]:
cleaned1617state = cleaned1617.iloc[:51]
cleaned1617state.head(52)
cleaned1617state['Code'] = code_col
cleaned1617state.head()

C:\Users\sarah\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,Flu Season,Location of Immunization,≥ 6 months,6 months - 17 years,6 months - 4 years,5 - 12 years,13 - 17 years,≥ 18 years,18 - 64 years,18 - 49 years,50 -64 years,≥ 65 years,Total Vaccinated,Code
2,2016-2017,Alabama,7901,2555,757,1196,602,5346,3393,1774,1619,1953,15802,AL
3,2016-2017,Alaska,4998,2238,688,971,579,2760,1989,980,1009,771,9996,AK
4,2016-2017,Arizona,11261,2357,706,1030,621,8904,4950,2486,2464,3954,22522,AZ
5,2016-2017,Arkansas,6418,2303,691,1027,585,4115,2075,896,1179,2040,12836,AR
6,2016-2017,California,8010,3095,1059,1348,688,4915,3726,2436,1290,1189,16020,CA

In [13]:
vac1718_df.head()
cleaned1718=vac1718_df.drop(columns=["Unnamed: 2","Influenza vaccination (General Population) - Age",
                        "Unnamed: 3","Unnamed: 4","Unnamed: 6","Unnamed: 99","Unnamed: 100","Unnamed: 101","Unnamed: 102","Unnamed: 103","Unnamed: 104",
                        "Unnamed: 105","Unnamed: 106","Unnamed: 7","Unnamed: 8","Unnamed: 9","Unnamed: 10","Unnamed: 12","Unnamed: 13","Unnamed: 14"
                                    ,"Unnamed: 15","Unnamed: 16","Unnamed: 18","Unnamed: 19","Unnamed: 20","Unnamed: 21","Unnamed: 22",
                                    "Unnamed: 24","Unnamed: 25","Unnamed: 26","Unnamed: 27","Unnamed: 28",
                                    "Unnamed: 30","Unnamed: 31","Unnamed: 32","Unnamed: 33","Unnamed: 34",
                                    "Unnamed: 36","Unnamed: 37","Unnamed: 38","Unnamed: 39","Unnamed: 40",
                                    "Unnamed: 42","Unnamed: 43","Unnamed: 44","Unnamed: 45","Unnamed: 46",
                                    "Unnamed: 48","Unnamed: 49","Unnamed: 50","Unnamed: 51","Unnamed: 52",
                                    "Unnamed: 54","Unnamed: 55","Unnamed: 56","Unnamed: 57","Unnamed: 58",
                                    "Unnamed: 91","Unnamed: 92","Unnamed: 93","Unnamed: 94","Unnamed: 95",
                                    "Unnamed: 60","Unnamed: 61","Unnamed: 62","Unnamed: 63","Unnamed: 64",
                                    "Unnamed: 66","Unnamed: 67","Unnamed: 68","Unnamed: 69","Unnamed: 70",
                                    "Unnamed: 72","Unnamed: 73","Unnamed: 74","Unnamed: 75","Unnamed: 76",
                                    "Unnamed: 78","Unnamed: 79","Unnamed: 80","Unnamed: 81","Unnamed: 82",
                                    "Unnamed: 84","Unnamed: 86","Unnamed: 87","Unnamed: 88",
                                    "Unnamed: 89","Unnamed: 90","Unnamed: 96","Unnamed: 97","Unnamed: 98",
                                    "Unnamed: 107","Unnamed: 108", "Influenza vaccination (General Population) - Race/ethnicity"])

cleaned1718=cleaned1718.drop([0,1],axis=0)
cleaned1718.head()

cleaned1718.rename(columns={"Unnamed: 0":"Location of Immunization"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 5":"≥ 6 months"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 11":"6 months - 17 years"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 17":"6 months - 4 years"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 23":"5 - 12 years"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 29":"13 - 17 years"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 35":"≥ 18 years"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 41":"18 - 64 years"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 59":"18 - 49 years"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 77":"50 -64 years"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 83":"≥ 65 years"},inplace=True)

del cleaned1718["Unnamed: 47"]
del cleaned1718["Unnamed: 53"]
del cleaned1718["Unnamed: 65"]
del cleaned1718["Unnamed: 71"]

cleaned1718.insert(0, 'Flu Season', '2017-2018')

In [14]:
cleaned1718.head(50)

,Flu Season,Location of Immunization,≥ 6 months,6 months - 17 years,6 months - 4 years,5 - 12 years,13 - 17 years,≥ 18 years,18 - 64 years,18 - 49 years,50 -64 years,≥ 65 years
2,2017-2018,Alabama,7547,2671,854,1224,593,4876,3030,1560,1470,1846
3,2017-2018,Alaska,3690,1752,564,719,469,1938,1311,718,593,627
4,2017-2018,Arizona,12285,2358,740,1120,498,9927,5985,3168,2817,3942
5,2017-2018,Arkansas,6287,2129,647,925,557,4158,2031,909,1122,2127
6,2017-2018,California,10838,2355,809,950,596,8483,6643,4380,2263,1840
7,2017-2018,Colorado,7765,1828,610,780,438,5937,4008,2266,1742,1929
8,2017-2018,Connecticut,9648,2182,648,1102,432,7466,4631,2134,2497,2835
9,2017-2018,Delaware,6437,2282,684,1078,520,4155,2699,1419,1280,1456
10,2017-2018,District of Columbia,4122,2545,807,1033,705,1577,1109,686,423,468
11,2017-2018,Florida,13044,2888,912,1279,697,10156,6029,3254,2775,4127
12,2017-2018,Georgia,9328,2776,876,1292,608,6552,4399,2558,1841,2153
13,2017-2018,Hawaii,7481,1995,608,857,530,5486,3636,2074,1562,1850
14,2017-2018,Idaho,4391,1682,487,625,570,2709,1700,992,708,1009
15,2017-2018,Illinois,8472,4184,1259,1733,1192,4288,2839,1628,1211,1449
16,2017-2018,Indiana,9863,2007,648,905,454,7856,4806,2403,2403,3050
17,2017-2018,Iowa,7712,1364,458,548,358,6348,4267,2384,1883,2081
18,2017-2018,Kansas,13771,1471,440,589,442,12300,7934,4226,3708,4366
19,2017-2018,Kentucky,8375,1748,554,719,475,6627,4553,2438,2115,2074
20,2017-2018,Louisiana,4291,2267,736,985,546,2024,1491,846,645,533
21,2017-2018,Maine,9298,2219,664,1099,456,7079,4119,1892,2227,2960
22,2017-2018,Maryland,14178,3006,944,1272,790,11172,6495,2954,3541,4677
23,2017-2018,Massachusetts,7426,2034,664,906,464,5392,3478,1841,1637,1914
24,2017-2018,Michigan,7542,1836,595,767,474,5706,3769,2137,1632,1937
25,2017-2018,Minnesota,17022,1702,524,659,519,15320,10558,5819,4739,4762
26,2017-2018,Mississippi,6283,2958,932,1481,545,3325,2065,1070,995,1260
27,2017-2018,Missouri,5994,1790,558,704,528,4204,2509,1340,1169,1695
28,2017-2018,Montana,4892,1817,583,758,476,3075,1873,944,929,1202
29,2017-2018,Nebraska,13038,1495,500,562,433,11543,7351,4135,3216,4192
30,2017-2018,Nevada,4645,2178,661,907,610,2467,1498,831,667,969
31,2017-2018,New Hampshire,6233,1996,598,958,440,4237,2506,1107,1399,1731
32,2017-2018,New Jersey,9526,2938,955,1347,636,6588,4183,2041,2142,2405
33,2017-2018,New Mexico,7400,2295,712,1146,437,5105,3271,1715,1556,1834
34,2017-2018,New York,22031,4200,1444,1693,1063,17831,12491,7076,5415,5340
35,2017-2018,North Carolina,5342,2411,766,1091,554,2931,2073,1263,810,858
36,2017-2018,North Dakota,4798,1698,569,667,462,3100,1919,962,957,1181
37,2017-2018,Ohio,12801,2236,740,928,568,10565,6387,3058,3329,4178
38,2017-2018,Oklahoma,6536,2357,772,1014,571,4179,2514,1342,1172,1665
39,2017-2018,Oregon,5197,1673,493,730,450,3524,2351,1358,993,1173
40,2017-2018,Pennsylvania,7117,4517,1454,1863,1200,2600,1886,1161,725,714
41,2017-2018,Rhode Island,6250,2133,628,1098,407,4117,2577,1222,1355,1540
42,2017-2018,South Carolina,10267,2451,751,1134,566,7816,4247,2051,2196,3569
43,2017-2018,South Dakota,8116,1643,519,683,441,6473,3921,1989,1932,2552
44,2017-2018,Tennessee,4963,1787,590,726,471,3176,2153,1220,933,1023
45,2017-2018,Texas,18715,10516,3588,3245,3683,8199,5350,3182,2168,2849
46,2017-2018,Utah,9382,1755,565,696,494,7627,5728,3940,1788,1899
47,2017-2018,Vermont,6936,1997,585,1031,381,4939,3086,1483,1603,1853
48,2017-2018,Virginia,9944,2623,862,1088,673,7321,4658,2416,2242,2663
49,2017-2018,Washington,10814,1972,664,807,501,8842,5583,3122,2461,3259
50,2017-2018,West Virginia,6542,2508,785,1160,563,4034,2510,1219,1291,1524
51,2017-2018,Wisconsin,6323,2032,637,868,527,4291,2807,1506,1301,1484

In [15]:
sum_col = cleaned1718['≥ 6 months'] + cleaned1718['6 months - 17 years'] + cleaned1718['≥ 18 years'] 
cleaned1718['Total Vaccinated'] = sum_col
cleaned1718.head()

,Flu Season,Location of Immunization,≥ 6 months,6 months - 17 years,6 months - 4 years,5 - 12 years,13 - 17 years,≥ 18 years,18 - 64 years,18 - 49 years,50 -64 years,≥ 65 years,Total Vaccinated
2,2017-2018,Alabama,7547,2671,854,1224,593,4876,3030,1560,1470,1846,15094
3,2017-2018,Alaska,3690,1752,564,719,469,1938,1311,718,593,627,7380
4,2017-2018,Arizona,12285,2358,740,1120,498,9927,5985,3168,2817,3942,24570
5,2017-2018,Arkansas,6287,2129,647,925,557,4158,2031,909,1122,2127,12574
6,2017-2018,California,10838,2355,809,950,596,8483,6643,4380,2263,1840,21676

In [16]:
cleaned1718state = cleaned1718.iloc[:51]
cleaned1718state.head(52)
cleaned1718state['Code'] = code_col
cleaned1718state.head()

C:\Users\sarah\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,Flu Season,Location of Immunization,≥ 6 months,6 months - 17 years,6 months - 4 years,5 - 12 years,13 - 17 years,≥ 18 years,18 - 64 years,18 - 49 years,50 -64 years,≥ 65 years,Total Vaccinated,Code
2,2017-2018,Alabama,7547,2671,854,1224,593,4876,3030,1560,1470,1846,15094,AL
3,2017-2018,Alaska,3690,1752,564,719,469,1938,1311,718,593,627,7380,AK
4,2017-2018,Arizona,12285,2358,740,1120,498,9927,5985,3168,2817,3942,24570,AZ
5,2017-2018,Arkansas,6287,2129,647,925,557,4158,2031,909,1122,2127,12574,AR
6,2017-2018,California,10838,2355,809,950,596,8483,6643,4380,2263,1840,21676,CA

In [17]:
vac1819_df.head()
cleaned1819=vac1819_df.drop(columns=["Unnamed: 2","Influenza vaccination (General Population) - Age",
                        "Unnamed: 3","Unnamed: 4","Unnamed: 6","Unnamed: 99","Unnamed: 100","Unnamed: 101","Unnamed: 102","Unnamed: 103","Unnamed: 104",
                        "Unnamed: 105","Unnamed: 106","Unnamed: 7","Unnamed: 8","Unnamed: 9","Unnamed: 10","Unnamed: 12","Unnamed: 13","Unnamed: 14"
                                    ,"Unnamed: 15","Unnamed: 16","Unnamed: 18","Unnamed: 19","Unnamed: 20","Unnamed: 21","Unnamed: 22",
                                    "Unnamed: 24","Unnamed: 25","Unnamed: 26","Unnamed: 27","Unnamed: 28",
                                    "Unnamed: 30","Unnamed: 31","Unnamed: 32","Unnamed: 33","Unnamed: 34",
                                    "Unnamed: 36","Unnamed: 37","Unnamed: 38","Unnamed: 39","Unnamed: 40",
                                    "Unnamed: 42","Unnamed: 43","Unnamed: 44","Unnamed: 45","Unnamed: 46",
                                    "Unnamed: 48","Unnamed: 49","Unnamed: 50","Unnamed: 51","Unnamed: 52",
                                    "Unnamed: 54","Unnamed: 55","Unnamed: 56","Unnamed: 57","Unnamed: 58",
                                    "Unnamed: 91","Unnamed: 92","Unnamed: 93","Unnamed: 94","Unnamed: 95",
                                    "Unnamed: 60","Unnamed: 61","Unnamed: 62","Unnamed: 63","Unnamed: 64",
                                    "Unnamed: 66","Unnamed: 67","Unnamed: 68","Unnamed: 69","Unnamed: 70",
                                    "Unnamed: 72","Unnamed: 73","Unnamed: 74","Unnamed: 75","Unnamed: 76",
                                    "Unnamed: 78","Unnamed: 79","Unnamed: 80","Unnamed: 81","Unnamed: 82",
                                    "Unnamed: 84","Unnamed: 86","Unnamed: 87","Unnamed: 88",
                                    "Unnamed: 89","Unnamed: 90","Unnamed: 96","Unnamed: 97","Unnamed: 98",
                                    "Unnamed: 107","Unnamed: 108", "Influenza vaccination (General Population) - Race/ethnicity"])

cleaned1819=cleaned1819.drop([0,1],axis=0)


cleaned1819.rename(columns={"Unnamed: 0":"Location of Immunization"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 5":"≥ 6 months"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 11":"6 months - 17 years"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 17":"6 months - 4 years"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 23":"5 - 12 years"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 29":"13 - 17 years"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 35":"≥ 18 years"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 41":"18 - 64 years"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 59":"18 - 49 years"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 77":"50 -64 years"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 83":"≥ 65 years"},inplace=True)

del cleaned1819["Unnamed: 47"]
del cleaned1819["Unnamed: 53"]
del cleaned1819["Unnamed: 65"]
del cleaned1819["Unnamed: 71"]

cleaned1819.insert(0, 'Flu Season', '2018-2019')

In [18]:
#drop NA values from not reported states
cleaned1819 = cleaned1819.drop([10,32])
cleaned1819.head(50)

,Flu Season,Location of Immunization,≥ 6 months,6 months - 17 years,6 months - 4 years,5 - 12 years,13 - 17 years,≥ 18 years,18 - 64 years,18 - 49 years,50 -64 years,≥ 65 years
2,2018-2019,Alabama,7966,2935,935,1380,620,5031,3071,1615,1456,1960
3,2018-2019,Alaska,4169,1683,522,598,563,2486,1699,902,797,787
4,2018-2019,Arizona,8714,2253,703,988,562,6461,3712,1975,1737,2749
5,2018-2019,Arkansas,5247,2352,739,1073,540,2895,1442,684,758,1453
6,2018-2019,California,9857,2275,893,860,522,7582,5639,3654,1985,1943
7,2018-2019,Colorado,9421,2096,680,871,545,7325,4824,2752,2072,2501
8,2018-2019,Connecticut,9274,1804,527,696,581,7470,4573,2152,2421,2897
9,2018-2019,Delaware,5758,2865,861,1473,531,2893,1873,1043,830,1020
11,2018-2019,Florida,18806,3234,1120,1244,870,15572,9098,4929,4169,6474
12,2018-2019,Georgia,7319,3212,1051,1528,633,4107,2805,1667,1138,1302
13,2018-2019,Hawaii,8433,2313,723,1024,566,6120,3910,2256,1654,2210
14,2018-2019,Idaho,3728,1617,497,684,436,2111,1366,816,550,745
15,2018-2019,Illinois,8441,4540,1468,1864,1208,3901,2768,1683,1085,1133
16,2018-2019,Indiana,9254,2533,825,1157,551,6721,4078,2120,1958,2643
17,2018-2019,Iowa,8797,1717,566,704,447,7080,4722,2751,1971,2358
18,2018-2019,Kansas,10097,2369,752,929,688,7728,4867,2670,2197,2861
19,2018-2019,Kentucky,5619,1657,517,663,477,3962,2583,1370,1213,1379
20,2018-2019,Louisiana,5407,2368,851,856,661,3039,2150,1225,925,889
21,2018-2019,Maine,10246,2363,695,1106,562,7883,4166,1749,2417,3717
22,2018-2019,Maryland,16938,4410,1534,2064,812,12528,7271,3338,3933,5257
23,2018-2019,Massachusetts,7770,2060,727,776,557,5710,3921,2266,1655,1789
24,2018-2019,Michigan,9132,2266,809,906,551,6866,4494,2573,1921,2372
25,2018-2019,Minnesota,10694,1744,551,703,490,8950,6037,3455,2582,2913
26,2018-2019,Mississippi,6900,3417,1099,1742,576,3483,2264,1201,1063,1219
27,2018-2019,Missouri,8597,1897,632,841,424,6700,3796,1972,1824,2904
28,2018-2019,Montana,6666,2097,703,949,445,4569,2900,1602,1298,1669
29,2018-2019,Nebraska,11617,1765,576,716,473,9852,6077,3368,2709,3775
30,2018-2019,Nevada,3854,2371,801,910,660,1483,1018,640,378,465
31,2018-2019,New Hampshire,6144,2387,739,1153,495,3757,2143,962,1181,1614
33,2018-2019,New Mexico,7277,2474,879,1031,564,4803,2994,1619,1375,1809
34,2018-2019,New York,23398,4921,1762,2022,1137,18477,12114,6642,5472,6363
35,2018-2019,North Carolina,6767,3390,1143,1605,642,3377,2380,1466,914,997
36,2018-2019,North Dakota,7313,1800,616,701,483,5513,3147,1487,1660,2366
37,2018-2019,Ohio,12308,2632,847,1182,603,9676,5725,2830,2895,3951
38,2018-2019,Oklahoma,7087,2955,964,1286,705,4132,2520,1415,1105,1612
39,2018-2019,Oregon,6325,1703,510,711,482,4622,3217,1991,1226,1405
40,2018-2019,Pennsylvania,11333,5161,1699,2159,1303,6172,4305,2493,1812,1867
41,2018-2019,Rhode Island,6699,2198,694,962,542,4501,2813,1359,1454,1688
42,2018-2019,South Carolina,9389,2968,976,1370,622,6421,3503,1838,1665,2918
43,2018-2019,South Dakota,7179,1956,632,802,522,5223,3191,1679,1512,2032
44,2018-2019,Tennessee,5775,2031,664,767,600,3744,2362,1233,1129,1382
45,2018-2019,Texas,20511,10954,3758,3407,3789,9557,5918,3442,2476,3639
46,2018-2019,Utah,10046,1719,583,690,446,8327,6037,4129,1908,2290
47,2018-2019,Vermont,7170,2411,717,1164,530,4759,2828,1288,1540,1931
48,2018-2019,Virginia,11249,3148,1130,1442,576,8101,5467,3062,2405,2634
49,2018-2019,Washington,12131,2185,763,932,490,9946,6012,3362,2650,3934
50,2018-2019,West Virginia,6964,2883,950,1359,574,4081,2471,1212,1259,1610
51,2018-2019,Wisconsin,5561,2600,822,1177,601,2961,1864,938,926,1097
52,2018-2019,Wyoming,5447,1957,643,894,420,3490,1958,964,994,1532
53,2018-2019,United States,441506,139358,46248,59141,33969,302148,190093,103839,86254,112055

In [19]:
sum_col = cleaned1819['≥ 6 months'] + cleaned1819['6 months - 17 years'] + cleaned1819['≥ 18 years'] 
cleaned1819['Total Vaccinated'] = sum_col
cleaned1819.head()
cleaned1819state = cleaned1819.iloc[:49]
cleaned1819state.head(52)
#take out DC and NJ from code col, because dropped those rows earlier
code_col2 = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", 
          "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", 
          "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", 
          "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", 
          "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]


cleaned1819state['Code'] = code_col2
cleaned1819state.head(50)

C:\Users\sarah\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Flu Season,Location of Immunization,≥ 6 months,6 months - 17 years,6 months - 4 years,5 - 12 years,13 - 17 years,≥ 18 years,18 - 64 years,18 - 49 years,50 -64 years,≥ 65 years,Total Vaccinated,Code
2,2018-2019,Alabama,7966,2935,935,1380,620,5031,3071,1615,1456,1960,15932,AL
3,2018-2019,Alaska,4169,1683,522,598,563,2486,1699,902,797,787,8338,AK
4,2018-2019,Arizona,8714,2253,703,988,562,6461,3712,1975,1737,2749,17428,AZ
5,2018-2019,Arkansas,5247,2352,739,1073,540,2895,1442,684,758,1453,10494,AR
6,2018-2019,California,9857,2275,893,860,522,7582,5639,3654,1985,1943,19714,CA
7,2018-2019,Colorado,9421,2096,680,871,545,7325,4824,2752,2072,2501,18842,CO
8,2018-2019,Connecticut,9274,1804,527,696,581,7470,4573,2152,2421,2897,18548,CT
9,2018-2019,Delaware,5758,2865,861,1473,531,2893,1873,1043,830,1020,11516,DE
11,2018-2019,Florida,18806,3234,1120,1244,870,15572,9098,4929,4169,6474,37612,FL
12,2018-2019,Georgia,7319,3212,1051,1528,633,4107,2805,1667,1138,1302,14638,GA
13,2018-2019,Hawaii,8433,2313,723,1024,566,6120,3910,2256,1654,2210,16866,HI
14,2018-2019,Idaho,3728,1617,497,684,436,2111,1366,816,550,745,7456,ID
15,2018-2019,Illinois,8441,4540,1468,1864,1208,3901,2768,1683,1085,1133,16882,IL
16,2018-2019,Indiana,9254,2533,825,1157,551,6721,4078,2120,1958,2643,18508,IN
17,2018-2019,Iowa,8797,1717,566,704,447,7080,4722,2751,1971,2358,17594,IA
18,2018-2019,Kansas,10097,2369,752,929,688,7728,4867,2670,2197,2861,20194,KS
19,2018-2019,Kentucky,5619,1657,517,663,477,3962,2583,1370,1213,1379,11238,KY
20,2018-2019,Louisiana,5407,2368,851,856,661,3039,2150,1225,925,889,10814,LA
21,2018-2019,Maine,10246,2363,695,1106,562,7883,4166,1749,2417,3717,20492,ME
22,2018-2019,Maryland,16938,4410,1534,2064,812,12528,7271,3338,3933,5257,33876,MD
23,2018-2019,Massachusetts,7770,2060,727,776,557,5710,3921,2266,1655,1789,15540,MA
24,2018-2019,Michigan,9132,2266,809,906,551,6866,4494,2573,1921,2372,18264,MI
25,2018-2019,Minnesota,10694,1744,551,703,490,8950,6037,3455,2582,2913,21388,MN
26,2018-2019,Mississippi,6900,3417,1099,1742,576,3483,2264,1201,1063,1219,13800,MS
27,2018-2019,Missouri,8597,1897,632,841,424,6700,3796,1972,1824,2904,17194,MO
28,2018-2019,Montana,6666,2097,703,949,445,4569,2900,1602,1298,1669,13332,MT
29,2018-2019,Nebraska,11617,1765,576,716,473,9852,6077,3368,2709,3775,23234,NE
30,2018-2019,Nevada,3854,2371,801,910,660,1483,1018,640,378,465,7708,NV
31,2018-2019,New Hampshire,6144,2387,739,1153,495,3757,2143,962,1181,1614,12288,NH
33,2018-2019,New Mexico,7277,2474,879,1031,564,4803,2994,1619,1375,1809,14554,NM
34,2018-2019,New York,23398,4921,1762,2022,1137,18477,12114,6642,5472,6363,46796,NY
35,2018-2019,North Carolina,6767,3390,1143,1605,642,3377,2380,1466,914,997,13534,NC
36,2018-2019,North Dakota,7313,1800,616,701,483,5513,3147,1487,1660,2366,14626,ND
37,2018-2019,Ohio,12308,2632,847,1182,603,9676,5725,2830,2895,3951,24616,OH
38,2018-2019,Oklahoma,7087,2955,964,1286,705,4132,2520,1415,1105,1612,14174,OK
39,2018-2019,Oregon,6325,1703,510,711,482,4622,3217,1991,1226,1405,12650,OR
40,2018-2019,Pennsylvania,11333,5161,1699,2159,1303,6172,4305,2493,1812,1867,22666,PA
41,2018-2019,Rhode Island,6699,2198,694,962,542,4501,2813,1359,1454,1688,13398,RI
42,2018-2019,South Carolina,9389,2968,976,1370,622,6421,3503,1838,1665,2918,18778,SC
43,2018-2019,South Dakota,7179,1956,632,802,522,5223,3191,1679,1512,2032,14358,SD
44,2018-2019,Tennessee,5775,2031,664,767,600,3744,2362,1233,1129,1382,11550,TN
45,2018-2019,Texas,20511,10954,3758,3407,3789,9557,5918,3442,2476,3639,41022,TX
46,2018-2019,Utah,10046,1719,583,690,446,8327,6037,4129,1908,2290,20092,UT
47,2018-2019,Vermont,7170,2411,717,1164,530,4759,2828,1288,1540,1931,14340,VT
48,2018-2019,Virginia,11249,3148,1130,1442,576,8101,5467,3062,2405,2634,22498,VA
49,2018-2019,Washington,12131,2185,763,932,490,9946,6012,3362,2650,3934,24262,WA
50,2018-2019,West Virginia,6964,2883,950,1359,574,4081,2471,1212,1259,1610,13928,WV
51,2018-2019,Wisconsin,5561,2600,822,1177,601,2961,1864,938,926,1097,11122,WI
52,2018-2019,Wyoming,5447,1957,643,894,420,3490,1958,964,994,1532,10894,WY

In [20]:
cleaned1516state.to_csv (r'vaccine1516data.csv', index = False, header=True)
cleaned1617state.to_csv (r'vaccine1617data.csv', index = False, header=True)
cleaned1718state.to_csv (r'vaccine1718data.csv', index = False, header=True)
cleaned1819state.to_csv (r'vaccine1819data.csv', index = False, header=True)